keys:
  # machines
  - &thelxinoe age1r983kf3l6n7ypjlq2cpuszr5a6euxlyugyvj2uc5zazer084v3tqncqurs
  - &janus age1xj3v4p5cz0elkxmvuzwxqkpwuxphs7k7k5qn4lp08d7lysq62axqatqwvf

  # users
  - &evie C0D9F9852861DA37BC9A875C45D28E7139388E21

creation_rules:
  - path_regex: secrets/secrets/secrets.yaml$
    shamir_treshold: 1
    key_groups:
    - pgp:
        - *evie
    - age:
        - *thelxinoe
        - *janus
  - path_regex: secrets/secrets/ect.yaml$
    shamir_treshold: 1
    key_groups:
    - pgp:
        - *evie
    - age:
        - *thelxinoe
        - *janus
