#+ATTR_HTML: :alt built with garnix
[[https://garnix.io/repo/eviefp/dotfiles][https://img.shields.io/endpoint.svg?url=https%3A%2F%2Fgarnix.io%2Fapi%2Fbadges%2Feviefp%2Fdotfiles]]

* My system configuration

Please let me know if you see anything dubious or that can be improved.

** Basic setup

This is a flake-based system configuration for my NixOS devices, with
system-wide settings being setup through NixOS modules and
personal/user settings being configured through the NixOS home-manager
module.

The basic structure is:

- =config= are random configuration files that are used in nix modules
- =dev-shell= has my default haskell setup
- =home-manager= has the HM modules and device configurations
- =system= has the NixOS modules and device configurations

** Initial setup

You will probably want to pick one of my devices as an example:

- =thelxinoe= is my desktop
- =janus= and =aiode= are my laptops
- =fractal= is my headless home server
- =thanatos= is my phone

#+BEGIN_SRC bash
sudo nixos-rebuild switch --flake .#newname
#+END_SRC

If you want to update the flake pins, you can run =nix flake update=.

** Vim/emacs configs

Vim: =config/nvim/lua/*.lua= (*)

Emacs: =config/init.el=

Helix: =home-manager/modules/programs/editors/helix.nix=

(*) My =init.lua= file is generated by nix as a require to all files under that directory. See =neovim.nix= for details.

** Sops stuff
For age keys

#+begin_src bash
nix-shell -p ssh-to-age
cat public_ed25519 | ssh-to-age # use this as the public key in the sops file
cat private_ed25519 | ssh-to-age -private-key # put this in ~/.config/sops/age/keys.txt
#+end_src

