* My system configuration

Please let me know if you see anything dubious or that can be improved.

** Basic setup

This is a flake-based system configuration for my NixOS devices, with
system-wide settings being setup through NixOS modules and
personal/user settings being configured through the NixOS home-manager
module.

The basic structure is:

- =config= are random configuration files that are used in nix modules
- =dev-shell= has my default haskell setup
- =home-manager= has the HM modules and device configurations
- =system= has the NixOS modules and device configurations

** Initial setup

You will probably want to pick one of my devices as an example:

- =thelxinoe= is my desktop
- =janus= and =aiode= are my laptops
- =fractal= is my headless home server

For example, start in =system/thelxinoe= and look around, understand
the modules and structure, etc.

Once that is done, you'll probably want to rename it and such.

You'll then want to go to =flake.nix= and rename =thenxinoe= to your
new name and try switching to the new config:

#+BEGIN_SRC bash
sudo nixos-rebuild switch --flake .#newname
#+END_SRC

If you want to update the flake pins, you can run =nix flake update=.

** Vim/emacs configs

Vim: =config/nvim/lua/*.lua= (*)

Emacs: =config/init.el=

(*) My `init.lua` file is generated by nix as a require to all files under that directory. See `neovim.nix` for details.

** TODO

- [ ] sddm styling
  - [ ] icon
- [ ] eww
  - [ ] statusbar
    - [ ] tray? WIP in eww, https://github.com/elkowar/eww/pull/743/files
    - [ ] clicking on cpu/memory/etc maybe opens more info?
  - [ ] another window that's some sort of overview?
- [-] hyprland
  - [-] screen sharing
    - [X] chromium and firefox work
    - [ ] qutebrowser doesn't work
    - [ ] did not test discord, zoom, etc.
- [ ] qutebrowser eating mouse (should be fixed in an update soon)
- [ ] swayimg: https://github.com/artemsen/swayimg/blob/master/extra/swayimgrc


awesome wayland https://github.com/natpen/awesome-wayland
