* My system configuration

Please let me know if you see anything dubious or that can be improved.

** Basic setup

This is a flake-based system configuration for my NixOS devices, with
system-wide settings being setup through NixOS modules and
personal/user settings being configured through the NixOS home-manager
module.

The basic structure is:

- =config= are random configuration files that are used in nix modules
- =dev-shell= has my default haskell setup
- =home-manager= has the HM modules and device configurations
- =system= has the NixOS modules and device configurations

** Initial setup

You will probably want to pick one of my devices as an example:

- =thelxinoe= is my desktop
- =janus= and =aiode= are my laptops
- =fractal= is my headless home server

For example, start in =system/thelxinoe= and look around, understand
the modules and structure, etc.

Once that is done, you'll probably want to rename it and such.

You'll then want to go to =flake.nix= and rename =thenxinoe= to your
new name and try switching to the new config:

#+BEGIN_SRC bash
sudo nixos-rebuild switch --flake .#newname
#+END_SRC

If you want to update the flake pins, you can run =nix flake update=.

** Vim/emacs configs

Vim: =config/nvim/lua/*.lua= (*)

Emacs: =config/init.el=

(*) My `init.lua` file is generated by nix as a require to all files under that directory. See `neovim.nix` for details.

** TODO

- [X] rofi config
  - [X] use same colors as eww
  - [X] transparent background
  - [X] rofi-pass
- [X] swaync config
  - [X] basic config
  - [X] eww integration
- [ ] sddm styling
- [ ] keyboard stuff, kmonad maybe?
  - [ ] this is terrible
  - [ ] maybe start here https://xkbcommon.org/doc/current/md_doc_2user-configuration.html
- [-] eww
  - [-] statusbar
    - [-] tray? WIP in eww, although not much progress lately?
      - [X] not sure I love the icons but I tried black both outline and fill and it's worse
      - [ ] clicking on cpu/memory/etc maybe opens more info?
      - [ ] turn on tv?
  - [ ] another window that's some sort of overview?
- [ ] discord: update start script to use ozone argument
- [-] hyprland
  - [X] styling/appearance
  - [X] workspace rules
  - [X] dwindle layout
  - [X] animations
  - [X] master layout
  - [ ] binds
    - [ ] microphone
    - [ ] switch audio? or just switch to tv?
  - [ ] screen sharing
- [ ] qutebrowser eating mouse (should be fixed in an update soon)
- [X] screenshot Super + M: grim + slurp + wl-copy
- [X] clipboard https://wiki.hyprland.org/Useful-Utilities/Clipboard-Managers/


awesome wayland https://github.com/natpen/awesome-wayland
other https://wiki.hyprland.org/Useful-Utilities/Other/
